<?php
namespace IciRelais;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-05 at 12:05:52.
 */
class IciRelaisTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var IciRelais
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IciRelais;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    public function testGetPrices()
    {
        $this->assertJsonStringEqualsJsonFile(__DIR__.IciRelais::JSON_PRICE_RESOURCE,json_encode($this->object->getPrices(),true));

    }
}
